# conda env create --file environment.yml
# mamba env create --file environment.yml
name: data_science_ibm
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - python=3.11
  - seaborn
  